#!/bin/bash
chars='[ !"#$&()*,;<>?\^`{|}]'
for arg
do
    if [[ $arg == *\'* ]]
    then
        arg=\""$arg"\"
    elif [[ $arg == *$chars* ]]
    then
        arg="'$arg'"
    fi
    allargs+=("$arg")    # ${allargs[@]} is to be used only for printing
done

ip="10.88.166.255"

if [ "x${CHINA_TEST_LOG}" != "x" ] ; then
  echo -n "$(basename $0) " >> ${CHINA_TEST_LOG}
  printf "%s " "${allargs[*]}" >> ${CHINA_TEST_LOG}
  echo -e "\n# returned $ip " >> ${CHINA_TEST_LOG}
fi

echo $ip
